# dropout:0.0
out_dir: results
dataset:
  format: PyG
  name: ZINC
  task: graph
  task_type: regression
  node_encoder: true
  node_encoder_name: Atom
  edge_encoder: False
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: mse
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_mp: 2
  layers_post_mp: 2
  dim_inner: 300
  layer_type: generalconv
  stage_type: stack
  batchnorm: true
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.0006
  max_epoch: 100
round: 6
metric_best: 'mae'
metric_agg: 'argmin'
# device: 'cuda:1'
